import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'ehenkan' at '5/13/16 10:56 AM' with Gradle 2.13
 *
 * @author ehenkan, @date 5/13/16 10:56 AM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {

    }
}
